base_dir:
  '/home/abd/Desktop/Work/Snakemake/bsm-search-snakemake/data/bsm-search'

code_dir:
  '/home/abd/Desktop/Work/Snakemake/bsm-search-snakemake/code'

thisroot_dir:
  '/home/abd/root/root/bin'

mc_options:
  mc1: { 'type': 'mc1', 'mcweight': '0.01875', 'nevents': '40000', 'njobs': 4 }
  mc2: { 'type': 'mc2', 'mcweight': '0.0125', 'nevents': '40000', 'njobs': 4 }

signal_options:
  sig: { 'type': 'sig', 'mcweight': '0.0025', 'nevents': '40000', 'njobs': 2 }

data_options:
  data: { 'type': 'data', 'nevents': '20000', 'njobs': 5 }

all_options:
  all: {}

select_mc_options:
  shape_conv_up: {'region': 'signal', 'variation': 'shape_conv_up', 'suffix': 'shape_conv_up' }
  shape_conv_dn: { 'region': 'signal', 'variation': 'shape_conv_dn', 'suffix': 'shape_conv_dn'}
  nominal: { 'region': 'signal', 'variation': 'nominal,weight_var1_up,weight_var1_dn', 'suffix': 'nominal' }

select_signal_options:
  nominal: {'region': 'signal','variation': 'nominal','suffix': 'nominal'}

select_data_options:
  signal: { 'region': 'signal', 'variation': 'nominal', 'suffix': 'signal' }
  control: { 'region': 'control', 'variation': 'nominal', 'suffix': 'control' }

hist_shape_mc_options:
  - 'shape_conv_up'
  - 'shape_conv_dn'

hist_weight_mc_options:
  - 'nominal'

hist_weight_data_options:
  data: { 'parent_type':'data', 'sub_type': 'signal', 'result':'data', 'weight': 1.0, 'shapevar': 'nominal' }
  qcd: { 'parent_type':'data', 'sub_type': 'control', 'result': 'qcd', 'weight': 0.1875, 'shapevar': 'nominal' }

hist_all_mc:
  - 'shape'
  - 'nominal'

hist_all_signal:
  - 'nominal'

hist_all_data:
  - 'data'
  - 'qcd'

hist_all:
  - 'mc1'
  - 'mc2'
  - 'sig'
  - 'data'

mc_weight_variations:
  mc1: "nominal,weight_var1_up,weight_var1_dn"
  mc2: "nominal,weight_var1_up,weight_var1_dn"

variations:
  mc1: 'nominal'
  mc2: 'nominal'
  sig: 'nominal'
  data: 'nominal'

makews_dir:
  - 'xmldir'
  - 'results'

makews_outputs:
  - "{base_dir}/xmldir"
  - "{base_dir}/results_results.table"
  - "{base_dir}/results_meas.root"
  - "{base_dir}/results_combined_meas_model.root"
  - "{base_dir}/results_combined_meas_profileLR.eps"
  - "{base_dir}/results_channel1_meas_profileLR.eps"
  - "{base_dir}/results_channel1_meas_model.root"

plot_outputs:
  - "{base_dir}/nominal_vals.yml"
  - "{base_dir}/fit_results.yml"
  - "{base_dir}/prefit.pdf"
  - "{base_dir}/postfit.pdf"
